[tool.poetry]
name = "kira-client"
version = "0.1.0"
description = ""
authors = ["Pavel Karpovich <pavel.karpovich@outlook.com>"]
readme = "README.md"
packages = [{include = "kira_client"}]

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.0.216"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
